version: '3.8'

services:
  sfeel_db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: miclave
      POSTGRES_DB: sfeeldb
    volumes:
      - /opt/docker/db_sfeel:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sfeeldb_lan
      
networks:
  sfeeldb_lan:
